<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBbf3zee\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBbf3zee/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBbf3zee.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBbf3zee\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBbf3zee\appDevDebugProjectContainer([
    'container.build_hash' => 'Bbf3zee',
    'container.build_id' => 'e43d39f2',
    'container.build_time' => 1579708518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBbf3zee');
